---
sidebar: sidebar 
permalink: reference-limits-aws.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM, ebs 
summary: O Cloud Volumes ONTAP tem limites de configuração de storage na AWS para fornecer operações confiáveis. Para obter o melhor desempenho, não configure o sistema com os valores máximos. 
---
= Limites de armazenamento na AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O Cloud Volumes ONTAP tem limites de configuração de storage para fornecer operações confiáveis. Para obter o melhor desempenho, não configure o sistema com os valores máximos.



== Capacidade máxima do sistema por licença

A capacidade máxima do sistema para um sistema Cloud Volumes ONTAP é determinada pela sua licença. A capacidade máxima do sistema inclui storage baseado em disco e storage de objetos usado para categorização de dados.

O NetApp não suporta exceder o limite de capacidade do sistema. Se você atingir o limite de capacidade licenciado, o BlueXP  exibirá uma mensagem de ação necessária e não permitirá mais adicionar discos adicionais.

Para algumas configurações, os limites de disco impedem que você alcance o limite de capacidade usando discos sozinhos. Nesses casos, você pode alcançar o limite de capacidade em https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["disposição em camadas dos dados inativos no storage de objetos"^]. Consulte os limites de capacidade e disco abaixo para obter mais detalhes.

[cols="25,75"]
|===
| Licença | Capacidade máxima do sistema (discos e armazenamento de objetos) 


| Freemium | 500 GiB 


| PAYGO Explore | 2 TIB (disposição de dados em categorias não é compatível com o Explore) 


| Padrão PAYGO | 10 TIB 


| PAYGO Premium | 368 TIB 


| Licença baseada em nó | 2 PIB (requer várias licenças) 


| Licença baseada em capacidade | 2 PIB 
|===
.No caso de HA, o limite de capacidade da licença por nó ou para todo o par de HA?
O limite de capacidade aplica-se a todo o par de HA. Não é por nó. Por exemplo, se você usar a licença Premium, poderá ter até 368 TIB de capacidade entre os dois nós.

.Para um sistema de HA na AWS, os dados espelhados contam com limite de capacidade?
Não, não. Os dados em um par de HA da AWS são espelhados de forma síncrona entre os nós para que os dados estejam disponíveis em caso de falha. Por exemplo, se você comprar um disco TIB de 8 TB no nó A, o BlueXP  também aloca um disco TIB de 8 TB no nó B que é usado para dados espelhados. Embora 16 TIB de capacidade tenha sido provisionado, apenas 8 TIB conta contra o limite de licença.



== Limites agregados

O Cloud Volumes ONTAP usa volumes EBS como discos e os agrupa em _agregados_. Agregados fornecem storage para volumes.

[cols="2*"]
|===
| Parâmetro | Limite 


| Número máximo de agregados | Nó único: O mesmo que os pares HA de limite de disco: 18 em um nó 1 


| Tamanho máximo do agregado 2  a| 
* 96 TIB de capacidade bruta
* 128 TIB de capacidade bruta com volumes elásticos 3




| Discos por agregado 4  a| 
* 1-6
* 1-8 com volumes elásticos 3




| Número máximo de grupos RAID por agregado | 1 
|===
Notas:

. Não é possível criar agregados 18 em ambos os nós em um par de HA porque isso excederia o limite do disco de dados.
. O tamanho máximo de agregado é baseado nos discos que compõem o agregado. O limite não inclui o storage de objetos usado para categorização de dados.
. Se você tiver uma configuração que suporte o recurso volumes elásticos do Amazon EBS, um agregado pode conter até 8 discos, o que fornece até 128 TIB de capacidade. O recurso volumes elásticos do Amazon EBS é ativado por padrão em sistemas _new_ Cloud Volumes ONTAP 9.11.0 ou posteriores ao usar discos GP3 ou IO1. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-aws-elastic-volumes.html["Saiba mais sobre o suporte para volumes elásticos"^]
. Todos os discos em um agregado devem ter o mesmo tamanho.




== Limites de disco e disposição em camadas por instância do EC2

Os limites de capacidade são diferentes dependendo da família de tipos de instância do EC2 usada e se você está usando um único sistema de nós ou um par de HA.

As notas a seguir fornecem detalhes sobre os números que você verá nas tabelas abaixo:

* Os limites de disco são específicos para discos que contêm dados de usuário.
+
Os limites não incluem o disco de inicialização e o disco raiz.

* A capacidade máxima do sistema é listada ao usar discos somente e ao usar discos e disposição em camadas de dados inativos no storage de objetos.
* O Cloud Volumes ONTAP usa volumes EBS como discos, com um tamanho máximo de disco de 16 TIB.




=== Limites para licenciamento baseado em capacidade

Os limites de disco a seguir se aplicam a sistemas Cloud Volumes ONTAP que usam um pacote de licenciamento baseado em capacidade. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html["Saiba mais sobre as opções de licenciamento do Cloud Volumes ONTAP"^]



==== Nó único

[cols="18,18,32,32"]
|===
| Instância | Máximo de discos por nó | Capacidade máxima do sistema somente com discos | Capacidade máxima do sistema com discos e categorização de dados 


| instâncias c5, m5 e r5 | 21 | 336 TIB | 2 PIB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 19 1 | 304 TIB | 2 PIB 
|===
. Esse tipo de instância tem mais discos NVMe locais do que outros tipos de instância, o que significa que um número menor de discos de dados é suportado.




==== Pares HA

[cols="18,18,32,32"]
|===
| Instância | Máximo de discos por nó | Capacidade máxima do sistema somente com discos | Capacidade máxima do sistema com discos e categorização de dados 


| instâncias c5, m5 e r5 | 18 | 288 TIB | 2 PIB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 16 1 | 256 TIB | 2 PIB 
|===
. Esse tipo de instância tem mais discos NVMe locais do que outros tipos de instância, o que significa que um número menor de discos de dados é suportado.




=== Limites para licenciamento baseado em nós

Os limites de disco a seguir se aplicam a sistemas Cloud Volumes ONTAP que usam licenciamento baseado em nós, que é o modelo de licenciamento da geração anterior que permitiu licenciar o Cloud Volumes ONTAP por nó. O licenciamento baseado em nós ainda está disponível para clientes existentes.

Você pode comprar várias licenças baseadas em nós para um sistema de nó único ou par de HA da Cloud Volumes ONTAP BYOL para alocar mais de 368 TIB de capacidade, até o limite máximo de capacidade do sistema testado e suportado de 2 PIB. Esteja ciente de que os limites de disco podem impedir que você alcance o limite de capacidade usando discos sozinhos. Você pode ir além do limite de disco pelo https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["disposição em camadas dos dados inativos no storage de objetos"^]. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-node-licenses.html["Saiba como adicionar licenças de sistema adicionais ao Cloud Volumes ONTAP"^]. Embora o Cloud Volumes ONTAP suporte até a capacidade máxima do sistema testada e suportada de 2 PIB, cruzar o limite de 2 PIB resulta em uma configuração de sistema não suportada.

As regiões de nuvem secreta da AWS e da nuvem secreta principal suportam a compra de várias licenças baseadas em nós a partir do Cloud Volumes ONTAP 9.12.1.



==== Nó único com PAYGO Premium

[cols="18,18,32,32"]
|===
| Instância | Máximo de discos por nó | Capacidade máxima do sistema somente com discos | Capacidade máxima do sistema com discos e categorização de dados 


| instâncias c5, m5 e r5 | 21 1 | 336 TIB | 368 TIB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 19 2 | 304 TIB | 368 TIB 
|===
. Os discos de dados 21 são o limite para _new_ implantações do Cloud Volumes ONTAP. Se você atualizar um sistema que foi criado com a versão 9,7 ou anterior, o sistema continuará a suportar 22 discos. Um disco de dados a menos é suportado em novos sistemas que usam esses tipos de instância por causa da adição de um disco núcleo começando com a versão 9,8.
. Esse tipo de instância tem mais discos NVMe locais do que outros tipos de instância, o que significa que um número menor de discos de dados é suportado.




==== Nó único com BYOL

[cols="18,18,16,16,16,16"]
|===
| Instância | Máximo de discos por nó 2+| Capacidade máxima do sistema com uma licença 2+| Capacidade máxima do sistema com várias licenças 


2+|  | *Discos sozinhos* | *Discos e categorização de dados* | *Discos sozinhos* | *Discos e categorização de dados* 


| instâncias c5, m5 e r5 | 21 1 | 336 TIB | 368 TIB | 336 TIB | 2 PIB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 19 2 | 304 TIB | 368 TIB | 304 TIB | 2 PIB 
|===
. Os discos de dados 21 são o limite para _new_ implantações do Cloud Volumes ONTAP. Se você atualizar um sistema que foi criado com a versão 9,7 ou anterior, o sistema continuará a suportar 22 discos. Um disco de dados a menos é suportado em novos sistemas que usam esses tipos de instância por causa da adição de um disco núcleo começando com a versão 9,8.
. Esse tipo de instância tem mais discos NVMe locais do que outros tipos de instância, o que significa que um número menor de discos de dados é suportado.




==== Pares DE HA com PAYGO Premium

[cols="18,18,32,32"]
|===
| Instância | Máximo de discos por nó | Capacidade máxima do sistema somente com discos | Capacidade máxima do sistema com discos e categorização de dados 


| instâncias c5, m5 e r5 | 18 1 | 288 TIB | 368 TIB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 16 2 | 256 TIB | 368 TIB 
|===
. Os discos de dados 18 são o limite para _new_ implantações do Cloud Volumes ONTAP. Se você atualizar um sistema que foi criado com a versão 9,7 ou anterior, o sistema continuará a suportar 19 discos. Um disco de dados a menos é suportado em novos sistemas que usam esses tipos de instância por causa da adição de um disco núcleo começando com a versão 9,8.
. Esse tipo de instância tem mais discos NVMe locais do que outros tipos de instância, o que significa que um número menor de discos de dados é suportado.




==== Pares DE HA com BYOL

[cols="18,18,16,16,16,16"]
|===
| Instância | Máximo de discos por nó 2+| Capacidade máxima do sistema com uma licença 2+| Capacidade máxima do sistema com várias licenças 


2+|  | *Discos sozinhos* | *Discos e categorização de dados* | *Discos sozinhos* | *Discos e categorização de dados* 


| instâncias c5, m5 e r5 | 18 1 | 288 TIB | 368 TIB | 288 TIB | 2 PIB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 16 2 | 256 TIB | 368 TIB | 256 TIB | 2 PIB 
|===
. Os discos de dados 18 são o limite para _new_ implantações do Cloud Volumes ONTAP. Se você atualizar um sistema que foi criado com a versão 9,7 ou anterior, o sistema continuará a suportar 19 discos. Um disco de dados a menos é suportado em novos sistemas que usam esses tipos de instância por causa da adição de um disco núcleo começando com a versão 9,8.
. Esse tipo de instância tem mais discos NVMe locais do que outros tipos de instância, o que significa que um número menor de discos de dados é suportado.




== Limites de VM de storage

Algumas configurações permitem que você crie VMs de storage adicionais (SVMs) para o Cloud Volumes ONTAP.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-aws.html["Saiba como criar VMs de armazenamento adicionais"^].

[cols="40,60"]
|===
| Tipo de licença | Limite da VM de storage 


| *Freemium*  a| 
24 VMs de armazenamento total 1,2



| * Capacidade baseada em PAYGO ou BYOL* 3  a| 
24 VMs de armazenamento total 1,2



| *PAYGO baseado em nós*  a| 
* VM de storage de 1 U para fornecimento de dados
* VM de storage de 1 U para recuperação de desastres




| * Baseado em nós BYOL* 4  a| 
* 24 VMs de armazenamento total 1,2


|===
. O limite pode ser menor, dependendo do tipo de instância EC2 que você usar. Os limites por instância estão listados na seção abaixo.
. Essas 24 VMs de storage podem fornecer dados ou ser configuradas para recuperação de desastres (DR).
. Para o licenciamento baseado em capacidade, não há custos adicionais de licenciamento para VMs de storage adicionais, mas há uma taxa de capacidade mínima de 4 TIB por VM de storage. Por exemplo, se você criar duas VMs de storage e cada uma tiver 2 TIB de capacidade provisionada, será cobrado um total de 8 TIB.
. Para o BYOL baseado em nós, é necessária uma licença complementar para cada VM de storage _data-service_ adicional além da primeira VM de storage fornecida com o Cloud Volumes ONTAP por padrão. Entre em Contato com sua equipe de conta para obter uma licença adicional de VM de storage.
+
As VMs de storage configuradas para recuperação de desastres (DR) não exigem uma licença complementar (elas são gratuitas), mas contam com o limite de VM de storage. Por exemplo, se você tiver 12 VMs de armazenamento de fornecimento de dados e 12 VMs de armazenamento configuradas para recuperação de desastres, atingiu o limite e não pode criar VMs de armazenamento adicionais.





=== Limite de VM de storage por tipo de instância EC2

Quando você cria uma VM de armazenamento adicional, você precisa alocar endereços IP privados à porta e0a. A tabela abaixo identifica o número máximo de IPs privados por interface, bem como o número de endereços IP disponíveis na porta e0a após a implantação do Cloud Volumes ONTAP. O número de endereços IP disponíveis afeta diretamente o número máximo de VMs de armazenamento para essa configuração.

As instâncias listadas abaixo são para as famílias de instâncias C5, M5 e R5.

[cols="6*"]
|===
| Configuração | Tipo de instância | Máximo de IPs privados por interface | IPS restantes após a implantação 1 | Máximo de VMs de armazenamento sem um mgmt LIF 2,3 | Máximo de VMs de armazenamento com um mgmt LIF 2,3 


.9+| * Nó único* | *. xlarge | 15 | 9 | 10 | 5 


| *.2xlarge | 15 | 9 | 10 | 5 


| *.4xlarge | 30 | 24 | 24 | 12 


| *.8xlarge | 30 | 24 | 24 | 12 


| *.9xlarge | 30 | 24 | 24 | 12 


| *.12xlarge | 30 | 24 | 24 | 12 


| *.16xlarge | 50 | 44 | 24 | 12 


| *.18xlarge | 50 | 44 | 24 | 12 


| *.24xlarge | 50 | 44 | 24 | 12 


.9+| *Par HA em único AZ* | *. xlarge | 15 | 10 | 11 | 5 


| *.2xlarge | 15 | 10 | 11 | 5 


| *.4xlarge | 30 | 25 | 24 | 12 


| *.8xlarge | 30 | 25 | 24 | 12 


| *.9xlarge | 30 | 25 | 24 | 12 


| *.12xlarge | 30 | 25 | 24 | 12 


| *.16xlarge | 50 | 45 | 24 | 12 


| *.18xlarge | 50 | 45 | 24 | 12 


| *.24xlarge | 50 | 44 | 24 | 12 


.9+| * Par HA em multi AZs* | *. xlarge | 15 | 12 | 13 | 13 


| *.2xlarge | 15 | 12 | 13 | 13 


| *.4xlarge | 30 | 27 | 24 | 24 


| *.8xlarge | 30 | 27 | 24 | 24 


| *.9xlarge | 30 | 27 | 24 | 24 


| *.12xlarge | 30 | 27 | 24 | 24 


| *.16xlarge | 50 | 47 | 24 | 24 


| *.18xlarge | 50 | 47 | 24 | 24 


| *.24xlarge | 50 | 44 | 24 | 12 
|===
. Esse número indica quantos endereços IP privados _restantes_ estão disponíveis na porta e0a depois que o Cloud Volumes ONTAP é implantado e configurado. Por exemplo, um sistema *.2xlarge suporta um máximo de 15 endereços IP por interface de rede. Quando um par de HA é implantado em uma única AZ, 5 endereços IP privados são alocados à porta e0a. Como resultado, um par de HA que usa um tipo de instância *.2xlarge tem 10 endereços IP privados restantes para VMs de storage adicionais.
. O número listado nessas colunas inclui a VM de armazenamento inicial que o BlueXP  cria por padrão. Por exemplo, se 24 estiver listado nesta coluna, isso significa que você pode criar 23 VMs de armazenamento adicionais para um total de 24.
. Um LIF de gerenciamento para a VM de storage é opcional. Um LIF de gerenciamento fornece uma conexão com ferramentas de gerenciamento como o SnapCenter.
+
Como ele requer um endereço IP privado, ele limitará o número de VMs de armazenamento adicionais que você pode criar. A única exceção é um par HA em vários AZs. Nesse caso, o endereço IP do LIF de gerenciamento é um endereço IP _flutuante_, portanto, ele não conta com o limite IP _private_.





== Limites de arquivo e volume

[cols="22,22,56"]
|===
| Storage lógico | Parâmetro | Limite 


.2+| *Ficheiros* | Tamanho máximo 2 | 128 TB 


| Máximo por volume | Depende do tamanho do volume, até 2 bilhões 


| *Volumes FlexClone* | Profundidade do clone hierárquico 1 | 499 


.3+| *Volumes FlexVol* | Máximo por nó | 500 


| Tamanho mínimo | 20 MB 


| Tamanho máximo 3 | 300 TIB 


| *Qtrees* | Máximo por FlexVol volume | 4.995 


| *Cópias Snapshot* | Máximo por FlexVol volume | 1.023 
|===
. Profundidade de clone hierárquica é a profundidade máxima de uma hierarquia aninhada de volumes FlexClone que pode ser criada a partir de um único FlexVol volume.
. Começando com ONTAP 9.12.1P2, o limite é de 128 TB. No ONTAP 9.11,1 e versões anteriores, o limite é de 16 TB.
. A criação do FlexVol volume até o tamanho máximo de 300 TIB é suportada usando as seguintes ferramentas e versões mínimas:
+
** O Gerenciador de sistemas e a CLI do ONTAP a partir do Cloud Volumes ONTAP 9.12.1 P2 e 9.13.0 P2
** BlueXP  a partir de Cloud Volumes ONTAP 9.13.1






== Limites de armazenamento iSCSI

[cols="3*"]
|===
| Armazenamento iSCSI | Parâmetro | Limite 


.4+| *LUNs* | Máximo por nó | 1.024 


| Número máximo de mapas LUN | 1.024 


| Tamanho máximo | 16 TIB 


| Máximo por volume | 512 


| *grupos* | Máximo por nó | 256 


.2+| *Iniciadores* | Máximo por nó | 512 


| Máximo por grupo | 128 


| * Sessões iSCSI* | Máximo por nó | 1.024 


.2+| *LIFs* | Máximo por porta | 32 


| Máximo por portset | 32 


| *Portsets* | Máximo por nó | 256 
|===