---
sidebar: sidebar 
permalink: reference-configs-gcp.html 
keywords: google, gcp, google cloud platform, explore, standard, premium, byol, paygo, disks, supported, capacity, machine types, sizes, HA, high availability, HA pairs 
summary: Várias configurações do Cloud Volumes ONTAP são compatíveis com o Google Cloud. 
---
= Configurações compatíveis com o Cloud Volumes ONTAP no Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Várias configurações do Cloud Volumes ONTAP são compatíveis com o Google Cloud.



== Configurações suportadas por licença

O Cloud Volumes ONTAP está disponível no Google Cloud como um sistema de nó único e como um par de nós de alta disponibilidade (HA) para tolerância de falhas e operações ininterruptas.

A atualização de um único sistema de nós para um par de HA não é compatível. Se você quiser alternar entre um único sistema de nós e um par de HA, precisará implantar um novo sistema e replicar dados do sistema existente para o novo sistema.

O Cloud Volumes ONTAP pode ser executado em uma instância de VM reservada ou sob demanda do seu provedor de nuvem. As soluções que usam outros tipos de instância de VM não são suportadas.

[role="tabbed-block"]
====
.Licenças baseadas em capacidade
--
[cols="h,d,d,d"]
|===
|  | Freemium | Otimizado ^4^ | Licença baseada em capacidade (Essentials e Professional) 


| Capacidade máxima do sistema (discos e armazenamento de objetos) | 500 GiB | 2 PIB | 2 PIB 


| Tipos de máquinas suportados 1  a| 
* n1-standard-8 1
* n1-standard-32 1
* n2-padrão-4
* n2-padrão-8
* n2-padrão-16
* n2-padrão-32
* n2-padrão-48
* n2-padrão-64

 a| 
* n2-padrão-4
* n2-padrão-8

 a| 
* n1-standard-8 1
* n1-standard-32 1
* n2-padrão-4
* n2-padrão-8
* n2-padrão-16
* n2-padrão-32
* n2-padrão-48
* n2-padrão-64




| Tipos de disco suportados 2 3+| Discos persistentes balanceados 3, discos persistentes Performance (SSD) 3 e discos persistentes Standard (HDD). 
|===
Notas:

. 1 as máquinas da série n1 não estão mais disponíveis para seleção no BlueXP  ao implantar novas instâncias do Cloud Volumes ONTAP no Google Cloud. As máquinas da série n1 serão mantidas e suportadas apenas em sistemas existentes mais antigos. Novas implantações do Cloud Volumes ONTAP são suportadas no Google Cloud apenas a partir da versão 9,8. Recomendamos que mude para as máquinas da série n2 compatíveis com o Cloud Volumes ONTAP 9,8 e posterior. As máquinas da série n1, no entanto, estarão disponíveis para novas implantações feitas através da API.
+
O tipo de máquina personalizado-4-16384 não é mais suportado com novos sistemas Cloud Volumes ONTAP. Se tiver um sistema existente a funcionar neste tipo de máquina, pode continuar a utilizá-lo, mas recomendamos que mude para o tipo de máquina n2-standard-4.

. 2 os limites de disco podem impedir que você alcance o limite máximo de capacidade do sistema usando discos sozinhos. Você pode alcançar o limite de capacidade por https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["disposição em camadas dos dados inativos no storage de objetos"^].
+
link:reference-limits-gcp.html["Saiba mais sobre os limites de disco no Google Cloud"].

. O desempenho de gravação aprimorado é habilitado ao usar discos persistentes balanceados e discos persistentes de desempenho (SSD). 3


A partir do Cloud Volumes ONTAP 9.13.0, _Flash Cache_, alta velocidade de gravação e uma unidade máxima de transmissão (MTU) mais alta de 8.896 bytes, estão disponíveis para as seguintes instâncias de implantação de par de HA:

* n2-padrão-16
* n2-padrão-32
* n2-padrão-48
* n2-padrão-64


Você pode ativar _Flash Cache_ e alta velocidade de gravação ao implantar um tipo de instância elegível. Para ativar a unidade máxima de transmissão superior de 8.896 bytes, você deve escolher VPC-1, VPC-2 ou VPC-3 para a implantação. A MTU mais alta permite maior taxa de transferência de rede. Para obter mais informações sobre como iniciar uma dessas implantações, https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-gcp.html#launching-an-ha-pair-in-google-cloud["Lançamento de um par de HA no Google Cloud"] consulte .


NOTE: _Flash cache_, modo de gravação alta e um MTU de 8.896 dependem de recursos e não podem ser desativados individualmente em uma instância configurada. . ^4^ A partir de 1º de julho de 2025, a licença Cloud Volumes ONTAP Optimized será descontinuada e não estará mais disponível para compra ou renovação no marketplace do Google Cloud para assinaturas de pagamento conforme o uso (PAYGO). Para obter informações, https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["O que há de novo no Cloud Volumes ONTAP"^] consulte .

--
.Licenças baseadas em nós
--
[cols="h,d,d,d,d"]
|===
|  | PAYGO Explore | Padrão PAYGO | PAYGO Premium | BYOL baseado em nós 


| Capacidade máxima do sistema (discos e armazenamento de objetos) | 2 TB 2 | 10 TIB | 368 TIB | 368 TIB por licença 


| Tipos de máquinas suportados 3  a| 
* n2-padrão-4

 a| 
* n1-standard-8 3
* n2-padrão-8

 a| 
* n1-standard-32 3
* n2-padrão-16
* n2-padrão-32
* n2-padrão-48
* n2-padrão-64

 a| 
* n1-standard-8 3
* n1-standard-32 3
* n2-padrão-4
* n2-padrão-8
* n2-padrão-16
* n2-padrão-32
* n2-padrão-48
* n2-padrão-64




| Tipos de disco suportados 4+| Discos persistentes balanceados 4, discos persistentes Performance (SSD) 4 e discos persistentes Standard (HDD). 
|===
Notas:

. 1 os limites de disco podem impedir que você alcance o limite máximo de capacidade do sistema usando discos sozinhos. Você pode alcançar o limite de capacidade por https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["disposição em camadas dos dados inativos no storage de objetos"^].
+
link:reference-limits-gcp.html["Saiba mais sobre os limites de disco no Google Cloud"].

. 2 a disposição de dados em camadas no Google Cloud Storage não é compatível com o PAYGO Explore.
. 3 as máquinas da série n1 não estão mais disponíveis para seleção no BlueXP  ao implantar novas instâncias do Cloud Volumes ONTAP no Google Cloud. As máquinas da série n1 serão mantidas e suportadas apenas em sistemas existentes mais antigos. Novas implantações do Cloud Volumes ONTAP são suportadas no Google Cloud apenas a partir da versão 9,8. Recomendamos que mude para as máquinas da série n2 compatíveis com o Cloud Volumes ONTAP 9,8 e posterior. As máquinas da série n1, no entanto, estarão disponíveis para novas implantações realizadas através da API.
+
O tipo de máquina personalizado-4-16384 não é mais suportado com novos sistemas Cloud Volumes ONTAP. Se tiver um sistema existente a funcionar neste tipo de máquina, pode continuar a utilizá-lo, mas recomendamos que mude para o tipo de máquina n2-standard-4.

. O desempenho de gravação aprimorado é habilitado ao usar discos persistentes balanceados e discos persistentes de desempenho (SSD). 4


A interface BlueXP  mostra um tipo de máquina compatível adicional para padrão e BYOL: N1-highmem-4. No entanto, este tipo de máquina não se destina a ambientes de produção. Disponibilizámos-o apenas para um ambiente de laboratório específico.

A partir do software Cloud Volumes ONTAP versão 9.13.0, _Flash Cache_, alta velocidade de gravação e uma unidade máxima de transmissão (MTU) mais alta de 8.896 bytes, estão disponíveis para as seguintes instâncias de implantação de par de HA:

* n2-padrão-16
* n2-padrão-32
* n2-padrão-48
* n2-padrão-64


Você pode ativar _Flash Cache_ e alta velocidade de gravação ao implantar um tipo de instância elegível. Para ativar a unidade máxima de transmissão superior de 8.896 bytes, você deve escolher VPC-1, VPC-2 ou VPC-3 para a implantação. A MTU mais alta permite maior taxa de transferência de rede. Para obter mais informações sobre como iniciar uma dessas implantações, https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-gcp.html#launching-an-ha-pair-in-google-cloud["Lançamento de um par de HA no Google Cloud"] consulte .


NOTE: _Flash cache_, modo de gravação alta e um MTU de 8.896 dependem de recursos e não podem ser desativados individualmente em uma instância configurada.

--
====
Para obter mais informações sobre tipos específicos de máquinas, consulte a documentação do Google Cloud:

* https://cloud.google.com/compute/docs/general-purpose-machines#n1_machines["Tipos de máquinas de uso geral da série n1"^]
* https://cloud.google.com/compute/docs/general-purpose-machines#n2_series["Tipos de máquinas de uso geral da série N2"^]




== Tamanhos de disco suportados

No Google Cloud, um agregado pode conter até 6 discos com o mesmo tipo e tamanho. Os seguintes tamanhos de disco são suportados:

* 100 GB
* 500 GB
* 1 TB
* 2 TB
* 4 TB
* 8 TB
* 16 TB
* 64 TB




== Regiões suportadas

Para obter suporte à região do Google Cloud, https://bluexp.netapp.com/cloud-volumes-global-regions["Regiões globais do Cloud volumes"^]consulte .
