---
sidebar: sidebar 
permalink: reference-limitations-gcp.html 
keywords: limitations, google cloud platform, gcp, psc, private service connect 
summary: As limitações conhecidas identificam plataformas, dispositivos ou funções que não são suportadas por esta versão do produto ou que não interoperam corretamente com ele. Revise essas limitações com cuidado. 
---
= Limitações conhecidas do Cloud Volumes ONTAP no Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
As limitações conhecidas a seguir são específicas do Cloud Volumes ONTAP no Google Cloud Platform. Certifique-se de também rever link:reference-limitations.html["Limitações do Cloud Volumes ONTAP em todos os fornecedores de nuvem"].



== Limitação com espelhamento de pacotes

https://cloud.google.com/vpc/docs/packet-mirroring["Espelhamento de pacotes"^] Deve ser desativado na VPC do Google na qual você implanta o Cloud Volumes ONTAP.

O Cloud Volumes ONTAP não pode funcionar corretamente se o espelhamento de pacotes estiver ativado.



== Limitações do Google Private Service Connect

Se você alavancar https://cloud.google.com/vpc/docs/private-service-connect["Google Private Service Connect"^] dentro da VPC na qual você está implantando o Cloud Volumes ONTAP , você precisará implementar registros DNS que encaminham o tráfego para o necessário https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-google.html["Pontos de extremidade da API"^] .

A disposição em camadas dos dados do Cloud Volumes ONTAP em um bucket do Google Cloud Storage não é compatível com o Private Service Connect.
