---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: O Cloud Volumes ONTAP 9.17.1 inclui um novo aprimoramento. 
---
= Novidades no Cloud Volumes ONTAP 9.17.1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O Cloud Volumes ONTAP 9.17.1 está disponível para implantação e atualização no Azure e no Google Cloud.



== 9.17.1 RC1 (4 de setembro de 2025)

Agora você pode usar o Release Candidate 1 do Cloud Volumes ONTAP 9.17.1 para implantação e atualização no Azure e no Google Cloud. No entanto, esta versão não está disponível para implantação e atualização na AWS.



== Notas de atualização

Leia estas notas para saber mais sobre a atualização para esta versão.



=== Como atualizar

As atualizações do Cloud Volumes ONTAP devem ser concluídas a partir do BlueXP . Você não deve atualizar o Cloud Volumes ONTAP usando o Gerenciador de sistema ou a CLI. Isso pode afetar a estabilidade do sistema.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["Saiba como atualizar quando o BlueXP  o notificar"^].



=== Caminho de atualização suportado

Você pode atualizar para o Cloud Volumes ONTAP 9.17.1 RC1 a partir da versão 9.16.1 no Azure e no Google Cloud.  O BlueXP solicitará que você atualize os sistemas Cloud Volumes ONTAP qualificados para esta versão.


NOTE: Para a AWS, você não será solicitado a fazer essa atualização.  A atualização para o Cloud Volumes ONTAP 9.17.1 RC1 não é suportada na AWS.



=== Tempo de inatividade

* A atualização de um sistema de nó único leva o sistema off-line por até 25 minutos, durante os quais a e/S é interrompida.
* A atualização de um par de HA não causa interrupções e e/S é ininterrupta. Durante esse processo de atualização sem interrupções, cada nó é atualizado em conjunto para continuar fornecendo e/S aos clientes.

