---
sidebar: sidebar 
permalink: reference-limitations-azure.html 
keywords: limitations, ha, azure, pay-as-you-go, paygo, cloud solution provider, vm, flash cache; limitations in HA deployment in MAZ, SAZ, multiple availability xone, single availability zone Azure CVO, PSSDv2, premium SSD v2 limitation in CVO, flash cache limitation in CVO 
summary: Essas limitações conhecidas são específicas do Cloud Volumes ONTAP no Microsoft Azure. 
---
= Limitações conhecidas para o Cloud Volumes ONTAP no Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
As seguintes limitações conhecidas são específicas do Cloud Volumes ONTAP no Microsoft Azure. Certifique-se de também rever link:reference-limitations.html["Limitações do Cloud Volumes ONTAP em todos os fornecedores de nuvem"].



== Limitações com o uso de extensões Azure VM

O Cloud Volumes ONTAP não oferece suporte a extensões de máquina virtual (VM) do Azure porque elas afetam as operações de gerenciamento do BlueXP .  Durante a implantação, o BlueXP impede a instalação de qualquer extensão em suas VMs.  Se as extensões já estiverem instaladas nas suas VMs Cloud Volumes ONTAP existentes, entre em contato com o Suporte do Microsoft Azure para removê-las.  Para obter orientação, consulte o artigo da base de conhecimento (KB) https://kb.netapp.com/Cloud/Cloud_Volumes_ONTAP/Can_Azure_VM_Management_Extensions_be_installed_into_Cloud_Volume_ONTAP["As extensões de gerenciamento de VM do Azure podem ser instaladas no Cloud Volume ONTAP?"^]

A partir de 14 de julho de 2025, a NetApp enviará e-mails e notificará você no BlueXP se extensões de VM forem detectadas em suas VMs do Cloud Volumes ONTAP .



== Limitações de discos SSD v2 premium para configurações de HA

Os discos gerenciados SSD v2 Premium têm as seguintes limitações para implantações de alta disponibilidade (HA) no Azure:

* Não suportado em implantações de HA em regiões não zonais.
* Não suportado em implantações de HA em várias zonas de disponibilidade.
* Suportado somente em configurações de HA implantadas em zonas de disponibilidade únicas.


Para usar discos gerenciados Premium SSD v2 com configurações de alta disponibilidade do Cloud Volumes ONTAP , certifique-se de que os seguintes requisitos sejam atendidos:

* A versão do Cloud Volumes ONTAP é 9.15.1 ou posterior.
* A implantação de HA está em uma única zona de disponibilidade do Azure.
* As regiões e zonas selecionadas oferecem suporte a discos gerenciados Premium SSD v2.  Para obter informações sobre as regiões suportadas, consulte o https://azure.microsoft.com/en-us/explore/global-infrastructure/products-by-region/["Site do Microsoft Azure: Produtos disponíveis por região"^] .


Para obter mais informações, consulte  https://docs.netapp.com/us-en/cloud-volumes-ontap-9151-relnotes/reference-new.html#support-for-premium-ssd-v2-managed-disks-in-azure["Suporte para discos gerenciados SSD v2 Premium no Azure"^] .



== Limitações com implantações de HA em zonas de disponibilidade únicas

A partir do Cloud Volumes ONTAP 9.15.1, você pode implantar instâncias de máquina virtual (VM) no modo HA em zonas de disponibilidade únicas (AZs) no Azure. Para obter informações sobre os critérios que suportam esse recurso, consulte https://docs.netapp.com/us-en/cloud-volumes-ontap-9151-relnotes/reference-new.html#deploy-ha-pairs-in-single-availability-zones-in-azure["Implante pares de HA em zonas de disponibilidade únicas no Azure"^] .

Se a versão do Cloud Volumes ONTAP for anterior a 9.15.1 ou se alguma dessas condições não for atendida, o modelo de implantação anterior que utiliza conjuntos de disponibilidade entrará em vigor. Isso se aplica apenas a configurações de HA.



== Limitações do Flash Cache

O Cloud Volumes ONTAP usa o storage NVMe local em alguns tipos de VM como _Flash Cache_. Observe esta limitação:

* O reaquecimento do cache após uma reinicialização não é suportado.




== Limitações com implantações de HA

Pares HA não são suportados em algumas regiões.

https://bluexp.netapp.com/cloud-volumes-global-regions["Veja a lista de regiões do Azure suportadas"^].
