---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: O Cloud Volumes ONTAP 9.17.1 inclui um novo aprimoramento. 
---
= Novidades no Cloud Volumes ONTAP 9.17.1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O Cloud Volumes ONTAP 9.17.1 inclui novos aprimoramentos.

Novos recursos do Cloud Volumes ONTAP também foram introduzidos nas versões mais recentes do NetApp Console. Para mais informações, veja as novidades em https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/whats-new.html["Cloud Volumes ONTAP"^] gerenciado no Console.



== 9.17.1 P1 (04 de novembro de 2025)

O patch Cloud Volumes ONTAP 9.17.1 P1 já está disponível para implantação e atualização na AWS, Azure e Google Cloud. O Console solicitará que você atualize seus sistemas existentes para esta versão de patch.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.17.1P1["Veja a lista de bugs corrigidos no patch P1"^](É necessário fazer login no site de suporte da NetApp ).



== 9.17.1 RC1 (4 de setembro de 2025)

Agora você pode usar o Release Candidate 1 do Cloud Volumes ONTAP 9.17.1 para implantação e atualização no Azure e no Google Cloud.


NOTE: Esta versão não está disponível para implantação e atualização na AWS.



== Notas de atualização

Leia estas notas para saber mais sobre a atualização para esta versão.



=== Como atualizar

As atualizações do Cloud Volumes ONTAP devem ser concluídas a partir do Console. Você não deve atualizar o Cloud Volumes ONTAP usando o System Manager ou a CLI. Isso pode afetar a estabilidade do sistema.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["Aprenda como fazer upgrade quando o Console notificar você"^] .



=== Caminho de atualização suportado

Você pode atualizar para o Cloud Volumes ONTAP 9.17.1 a partir da versão 9.16.1 na AWS, Azure e Google Cloud.  Para AWS, você pode atualizar para o Cloud Volumes ONTAP 9.17.1 P1 ou posterior.  O Console solicitará que você atualize os sistemas Cloud Volumes ONTAP elegíveis para esta versão.



=== Tempo de inatividade

* A atualização de um sistema de nó único leva o sistema off-line por até 25 minutos, durante os quais a e/S é interrompida.
* A atualização de um par de HA não causa interrupções e e/S é ininterrupta. Durante esse processo de atualização sem interrupções, cada nó é atualizado em conjunto para continuar fornecendo e/S aos clientes.

