---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: O Cloud Volumes ONTAP 9.15.1 inclui uma nova melhoria. 
---
= Novidades do Cloud Volumes ONTAP 9.15.1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O Cloud Volumes ONTAP 9.15.1 inclui novos aprimoramentos.

Recursos e aprimoramentos adicionais também são introduzidos nas versões mais recentes do BlueXP . Consulte https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Notas de versão do BlueXP "^] para obter detalhes.



== 9.15.1 P3 (29 de outubro de 2024)

O patch 9.15.1 P3 já está disponível para o Cloud Volumes ONTAP para todos os provedores de nuvem. O BlueXP  solicitará que você atualize seus sistemas existentes para esta versão de patch.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.15.1P3["Veja a lista de bugs corrigidos no patch P3"^] (É necessário iniciar sessão no site de suporte da NetApp).



== 9.15.1 P2 (14 de outubro de 2024)

O patch 9.15.1 P2 já está disponível para o Cloud Volumes ONTAP para todos os provedores de nuvem. O BlueXP  solicitará que você atualize seus sistemas existentes para esta versão de patch.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.15.1P2["Veja a lista de bugs corrigidos no patch P2"^] (É necessário iniciar sessão no site de suporte da NetApp).



== 9.15.1 P1 (3 de setembro de 2024)

O patch 9.15.1 P1 já está disponível para o Cloud Volumes ONTAP para todos os provedores de nuvem. O BlueXP  solicitará que você atualize seus sistemas existentes para esta versão de patch.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.15.1P1["Veja a lista de bugs corrigidos no patch P1"^] (É necessário iniciar sessão no site de suporte da NetApp).



== 9.15.1 GA (22 de Agosto de 2024)

O Cloud Volumes ONTAP 9.15.1 GA já está disponível na AWS, Azure e Google Cloud. A versão GA está disponível para implementação e atualização.

Esta versão inclui os seguintes recursos e aprimoramentos para o Azure. Continue lendo para saber mais sobre as configurações específicas que suportam esses novos recursos.



=== Suporte para discos gerenciados Premium SSD v2 no Azure

Os discos gerenciados premium SSD v2 agora são suportados em sistemas Cloud Volumes ONTAP no Azure. Esses discos premium fornecem desempenho mais alto com latência mais baixa a um custo menor para pares de nó único e de alta disponibilidade (HA), em comparação com discos gerenciados SSD Premium. Como outros discos gerenciados, o tamanho máximo do disco é de 32 TIB. É possível configurar o desempenho (capacidade, taxa de transferência e IOPS) de um disco gerenciado SSD v2 Premium, permitindo que os workloads sejam econômicos, atendendo às mudanças nas necessidades de desempenho.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-storage.html#azure-storage["Saiba mais sobre o armazenamento Azure"^].



=== Implante pares de HA em zonas de disponibilidade únicas no Azure

A partir do Cloud Volumes ONTAP 9.15.1, é possível implantar instâncias de máquina virtual (VM) no modo HA em zonas de disponibilidade únicas (AZs) no Azure. Ao contrário das implantações não zonais anteriores, o Cloud Volumes ONTAP 9.15.1 usa conjuntos de escala de máquinas virtuais da Microsoft no modo de orquestração flexível para implantar todos os recursos, incluindo domínios de falha separados dentro da mesma AZ, garantindo a disponibilidade ideal. Este modo de implantação, por padrão, usa discos gerenciados Premium SSD v2 quando os seguintes critérios são atendidos:

* A versão do Cloud Volumes ONTAP é 9.15.1 ou posterior.
* A região e a zona selecionadas suportam discos gerenciados Premium SSD v2. Para obter informações sobre as regiões suportadas,  https://azure.microsoft.com/en-us/explore/global-infrastructure/products-by-region/["Site do Microsoft Azure: Produtos disponíveis por região"^]consulte . Para saber como adicioná-los, https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-otc-azure.html#launching-a-cloud-volumes-ontap-ha-pair-in-azure["Lançamento de um par de HA do Cloud Volumes ONTAP no Azure"^] consulte .
* A assinatura está registrada para o recurso Microsoft `Microsoft.Compute/VMOrchestratorZonalMultiFD`. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-saz-feature.html["Saiba como ativar o VMOrchestratorZonalMultiFD para zonas de disponibilidade únicas"^].


Se algum desses critérios não for cumprido, o modo de implantação não zonal anterior para armazenamento localmente redundante (LRS) torna-se efetivo.



=== Suporte para conjuntos de dimensionamento de máquinas virtuais para unificar todos os tipos de HA do Azure

O Cloud Volumes ONTAP 9.15.1 utiliza conjuntos de escala de máquinas virtuais no modo de orquestração flexível no Azure para implantar instâncias de máquina virtual (VM) em zonas de disponibilidade únicas para pares de alta disponibilidade (HA). Ele cobre todos os sabores do modo HA, blob de página, LRS, armazenamento redundante de zona (ZRS) ou multi-zonal, e LRS zonal (AZ único).

* https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/["Documentação do Microsoft Azure: A escala de Máquina Virtual define a documentação"^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha-azure.html["Saiba mais sobre pares de alta disponibilidade no Azure"^].




== Notas de atualização.

Leia estas notas para saber mais sobre a atualização para esta versão.



=== Como atualizar

As atualizações do Cloud Volumes ONTAP devem ser concluídas a partir do BlueXP . Você não deve atualizar o Cloud Volumes ONTAP usando o Gerenciador de sistema ou a CLI. Isso pode afetar a estabilidade do sistema.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["Saiba como atualizar quando o BlueXP  o notificar"^].



=== Caminho de atualização suportado

Você pode atualizar para o Cloud Volumes ONTAP 9.15.1 a partir de versões 9.15.0 e 9.14.1. A BlueXP  solicitará que você atualize os sistemas Cloud Volumes ONTAP qualificados para esta versão.



=== Tempo de inatividade

* A atualização de um sistema de nó único leva o sistema off-line por até 25 minutos, durante os quais a e/S é interrompida.
* A atualização de um par de HA não causa interrupções e e/S é ininterrupta. Durante esse processo de atualização sem interrupções, cada nó é atualizado em conjunto para continuar fornecendo e/S aos clientes.




=== as instâncias c4, m4 e r4 não são mais compatíveis

Na AWS, os tipos de instância C4, M4 e R4 EC2 não são mais compatíveis com o Cloud Volumes ONTAP. Se você tiver um sistema existente que esteja sendo executado em um tipo de instância C4, M4 ou R4, será necessário alterar para um tipo de instância na família de instâncias C5, M5 ou R5. Não é possível atualizar para esta versão até alterar o tipo de instância.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["Saiba como alterar o tipo de instância EC2 para Cloud Volumes ONTAP"^].

link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["Suporte à NetApp"^]Consulte para saber mais sobre o fim da disponibilidade e suporte para esses tipos de instância.
