---
sidebar: sidebar 
permalink: reference-limitations-azure.html 
keywords: limitations, ha, azure, pay-as-you-go, paygo, cloud solution provider, vm, flash cache 
summary: Essas limitações conhecidas são específicas do Cloud Volumes ONTAP no Microsoft Azure. 
---
= Limitações conhecidas para o Cloud Volumes ONTAP no Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
As seguintes limitações conhecidas são específicas do Cloud Volumes ONTAP no Microsoft Azure. Certifique-se de também rever link:reference-limitations.html["Limitações do Cloud Volumes ONTAP em todos os fornecedores de nuvem"].



== Limitações com o uso de extensões Azure VM

O Cloud Volumes ONTAP não oferece suporte a extensões de máquina virtual (VM) do Azure porque elas atrasam as operações. Após a implantação do Cloud Volumes ONTAP, o BlueXP desabilita periodicamente as extensões de VM. Se você instalou essas extensões em seu ambiente de trabalho, entre em contato com o Suporte do Microsoft Azure para desabilitá-las ou excluí-las.



== Limitações do Flash Cache

O Cloud Volumes ONTAP usa o storage NVMe local em alguns tipos de VM como _Flash Cache_. Observe esta limitação:

* O reaquecimento do cache após uma reinicialização não é suportado.




== Limitações com implantações de alta disponibilidade

Pares de alta disponibilidade (HA) não são compatíveis em algumas regiões.

https://bluexp.netapp.com/cloud-volumes-global-regions["Veja a lista de regiões do Azure suportadas"^].



== Limitações com implantações de HA em zonas de disponibilidade únicas

A partir do Cloud Volumes ONTAP 9.15.1, é possível implantar instâncias de máquina virtual (VM) no modo HA em zonas de disponibilidade únicas (AZs) no Azure. Para obter informações sobre os critérios que suportam este recurso, https://docs.netapp.com/us-en/cloud-volumes-ontap-9151-relnotes/reference-new.html#deploy-ha-pairs-in-single-availability-zones-on-azure["Implante pares de HA em zonas de disponibilidade únicas no Azure"^] consulte .

Se a versão do Cloud Volumes ONTAP for anterior a 9.15.1 ou se alguma dessas condições não for atendida, o modelo de implantação anterior que utiliza conjuntos de disponibilidade entrará em vigor. Isso se aplica apenas a configurações de HA.
